apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-pvc-dpv
spec:
    storageClassName: fast #指定请求自定义的存储类型，最终由定义的storage class中的provisioner指定的卷插件创建对应的pv
    resources:
        storage: 100Mi
    accessModes:
    - ReadWriteOnce