apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-pvc-dpv2
spec:                     #没有指定storageClassName，采用默认的sc
    resources: 
        requests:
            storage: 100Mi
    accessModes:
        - ReadWriteOnce
